# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: frontend
      image: <name>
      ports:
      - containerPort: 3000

# Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
    