# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: newsfeed
    spec:
      containers:
      - name: frontend
        image: gcr.io/newsfeed-django/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: newsfeed
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: newsfeed
    