# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newsfeed
  labels:
    app: newsfeed
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: newsfeed
    spec:
      containers:
      - name: newsfeed-app
        image: gcr.io/newsfeed-django/newsfeed
        # The Pull policy is useful for debugging, but should be turned off in
        # production
        imagePullPolicy: Always
        env:
            # cloudsql secrets
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password
        ports:
        - containerPort: 8080
      
      # proxy container
      - image: gcr.io/cloudsql-docker/gce-proxy:1.05
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=newsfeed-django:us-central1:newsfeed-instance=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-oauth-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      # volumes:
      volumes:
        - name: cloudsql-oath-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:

# Service
# This service provides an HTTP load balancing proxy over the newsfeed app
apiVersion: v1
kind: Service
metadata:
  name: newsfeed
  labels:
    app: newsfeed
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: newsfeed
