# Deployment
apiVersion: extensions/v1betav1
kind: Deployment
metadata:
  name: newsfeed
  labels:
    app: newsfeed
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: newsfeed
    spec:
      containers:
      - name: newsfeed-app

# Service
# This service provides an HTTP load balancing proxy over the newsfeed app
apiVersion: v1
kind: Service
metadata:
  name: newsfeed
  labels:
    app: newsfeed
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: newsfeed
