version: '3.6'

services:
  postgres:
    hostname: postgres
    image: postgres
    ports:
      - "5432:5432"

  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
