# Generated by Django 2.1.2 on 2018-10-14 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, null=True, upload_to='thumbnail')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='articles')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('subject', models.CharField(choices=[('business', 'Business'), ('arts', 'Arts'), ('tech', 'Tech'), ('sports', 'Sports'), ('lifestyle', 'Lifestyle'), ('culture', 'Culture'), ('travel', 'Travel'), ('opinion', 'Opinion'), ('politics', 'Politics'), ('national', 'National'), ('world', 'World')], default='arts', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='articles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='articles.Author'),
        ),
    ]
