# Generated by Django 2.1.2 on 2019-01-03 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(choices=[('tech', 'Tech'), ('business', 'Business'), ('world', 'World'), ('science', 'Science')], default='science', max_length=9),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
