# Generated by Django 2.2.2 on 2019-10-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_whats_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='whats_news',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
