# Generated by Django 2.0.6 on 2018-07-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='about')),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
