# Generated by Django 2.0.6 on 2018-07-05 01:12

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, null=True, upload_to='thumbnail')),
                ('author', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='news')),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
