# Generated by Django 2.0.6 on 2018-07-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
