# Generated by Django 2.0.6 on 2018-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180705_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('ARTS', 'Arts'), ('TECH', 'Tech'), ('SPORTS', 'Sports'), ('LIFESTYLE', 'Lifestyle'), ('CULTURE', 'Culture'), ('TRAVEL', 'Travel'), ('OPINION', 'Opinion'), ('POLITICS', 'Politics'), ('NATIONAL', 'National'), ('WORLD', 'World')], default='ARTS', max_length=9),
        ),
    ]
